lib/wolves_web/router.ex
defmodule WolvesWeb.Router do
  use WolvesWeb, :router

  import WolvesWeb.AdminAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {WolvesWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_admin
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WolvesWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", WolvesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: WolvesWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", WolvesWeb do
    pipe_through [:browser, :redirect_if_admin_is_authenticated]


    get "/admins/log_in", AdminSessionController, :new
    post "/admins/log_in", AdminSessionController, :create
    get "/admins/reset_password", AdminResetPasswordController, :new
    post "/admins/reset_password", AdminResetPasswordController, :create
    get "/admins/reset_password/:token", AdminResetPasswordController, :edit
    put "/admins/reset_password/:token", AdminResetPasswordController, :update
  end

  scope "/", WolvesWeb do
    pipe_through [:browser, :require_authenticated_admin]

    get "/admins/settings", AdminSettingsController, :edit
    put "/admins/settings", AdminSettingsController, :update
    get "/admins/settings/confirm_email/:token", AdminSettingsController, :confirm_email
    live "/admin", AdminLive
    resources "/events", EventController
    resources "/players", PlayerController
    resources "/matches", MatchController
    get "/admins/register", AdminRegistrationController, :new
    post "/admins/register", AdminRegistrationController, :create
  end

  scope "/", WolvesWeb do
    pipe_through [:browser]

    delete "/admins/log_out", AdminSessionController, :delete
    get "/admins/confirm", AdminConfirmationController, :new
    post "/admins/confirm", AdminConfirmationController, :create
    get "/admins/confirm/:token", AdminConfirmationController, :edit
    post "/admins/confirm/:token", AdminConfirmationController, :update
  end
end

lib/wolves_web/views/layout_view.ex
defmodule WolvesWeb.LayoutView do
  use WolvesWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/wolves_web/templates/layout/_admin_menu.html.heex
<ul>
<%= if @current_admin do %>
  <li><%= @current_admin.email %></li>
  <li><%= link "Settings", to: Routes.admin_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.admin_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Register", to: Routes.admin_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.admin_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/wolves_web/templates/layout/app.html.heex
<%= @inner_content %>

lib/wolves_web/templates/layout/live.html.heex
<%= @inner_content %>

lib/wolves_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "СКТМ", suffix: " · Морски Вълци - Бургас" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script src="https://kit.fontawesome.com/33e4ec6f9a.js" crossorigin="anonymous"></script>
     <script src="https://unpkg.com/boxicons@2.1.2/dist/boxicons.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  </head>
  <body> 
  <%= if @current_admin do %>
    <%= render WolvesWeb.LayoutView, "_admin_menu.html", assigns %>
  <% end %>   
    <%= @inner_content %>
      <div class="credits">
  Сайтът е изработен от <a target="_blank" href="https://bratac.net"> Bratac.net </a>
  </div>
  </body>
</html>